import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Box, Heading, Text, VStack, Container } from '@chakra-ui/react';
import { useAuth } from '@/contexts/AuthContext';
import NextLink from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { currentUser } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container maxW="container.md" py={12}>
          <VStack spacing={8} textAlign="center">
            <Heading as="h1" size="2xl">
              Todoアプリへようこそ
            </Heading>
            <Text fontSize="xl">
              効率的にタスクを管理し、生産性を向上させましょう。
            </Text>
            
            {currentUser ? (
              <NextLink href="/dashboard" passHref>
                <Button colorScheme="teal" size="lg">
                  ダッシュボードへ
                </Button>
              </NextLink>
            ) : (
              <VStack spacing={4}>
                <NextLink href="/login" passHref>
                  <Button colorScheme="teal" size="lg" width="200px">
                    ログイン
                  </Button>
                </NextLink>
                <NextLink href="/signup" passHref>
                  <Button colorScheme="teal" variant="outline" size="lg" width="200px">
                    新規登録
                  </Button>
                </NextLink>
              </VStack>
            )}
          </VStack>
        </Container>
      </main>
    </>
  )
}
